version: "2"
linters:
  default: none
  enable:
    - errcheck
    - govet
    - revive
    - unused
    - staticcheck
  settings:
    revive:
      rules:
        - name: exported
          disabled: true
    staticcheck:
      checks:
        - all
        - -QF* # style suggestions, enable later
  exclusions:
    rules:
      - path: _test\.go
        linters:
          - errcheck
formatters:
  enable:
    - gofmt
